-- ===================================
-- Grupo G03
-- ===================================
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'PUT', 'administrador,responsable_secretaria,secretaria,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/status');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/reprint');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,responsable_secretaria,secretaria, tecnico_laboratorio, bioquimico', NULL, '/api/v1/labels/protocol/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'DELETE', 'administrador', NULL, '/api/v1/labels/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'PATCH', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador', NULL, '/api/v1/ping');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}/reprint-info');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}/print-history');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}/history');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/status/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/section/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/scan/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/protocol/{id}/print-history');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/protocol/{id}/patient-name');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/protocol/{id}/filter');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/analysis/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,responsable_secretaria,secretaria,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/active');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,responsable_secretaria,secretaria,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/attention-notification');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/discardable');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/{id}/discard');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/protocols/{id}/track-statuses');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/labels/protocols/track-statuses');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,tecnico_laboratorio,bioquimico,extractor', NULL, '/api/v1/labels/collect');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/reports/labels/status-counts');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/reports/labels/daily-created');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/reports/labels/avg-time-between-statuses');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/reports/labels/urgent');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/reports/labels/home-service');

-- Endpoints publicos para G03 - analytical
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/templates/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'PUT', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/templates/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/templates');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/templates');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/results');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'POST', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/results/ready/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/templates/name/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/pdf/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/worksheets/forms/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/results/sample/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/results/analysis/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador', NULL, '/api/v1/ping');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/analyses/{id}');
INSERT INTO endpoint_permissions (is_public, created_at, http_method, allowed_roles, description, endpoint_path) VALUES (false, NOW(), 'GET', 'administrador,tecnico_laboratorio,bioquimico', NULL, '/api/v1/analyses/basic');
